data:
  tokenizer: null
  train_files: /n/home12/cfpark00/ML/toy-multistep-reasoning/data/parquet_data_v5_3/train_rl.parquet
  val_files: /n/home12/cfpark00/ML/toy-multistep-reasoning/data/parquet_data_v5_3/test.parquet
  prompt_key: raw_prompt
  max_prompt_length: 64
  max_response_length: 64
  train_batch_size: 64
  val_batch_size: 512
  shuffle: True

actor_rollout_ref:
  model:
    path: /n/home12/cfpark00/ML/toy-multistep-reasoning/data/sft/v5/toy-multistep-v5-3/checkpoint-3125
    enable_gradient_checkpointing: True
    use_remove_padding: True
  actor:
    ppo_mini_batch_size: 64
    ppo_micro_batch_size_per_gpu: 64
    use_dynamic_bsz: True
    ppo_max_token_len_per_gpu: 16384
    grad_clip: 0.05
    clip_ratio: 0.2
    entropy_coeff: 0.001
    use_kl_loss: True
    kl_loss_coef: 0.001
    kl_loss_type: low_var_kl
    ppo_epochs: 4
    optim:
      lr: 3e-5
      lr_warmup_steps_ratio: 0.
      min_lr_ratio: null
      warmup_style: constant
      total_training_steps: -1
    fsdp_config:
      param_offload: False
      grad_offload: False
      optimizer_offload: False

  ref:
    fsdp_config:
      param_offload: True
  rollout:
    name: vllm
    temperature: 1.0
    top_k: -1
    top_p: 1
    prompt_length: 64
    response_length: 64
    dtype: bfloat16
    gpu_memory_utilization: 0.8
    tensor_model_parallel_size: 1
    max_num_batched_tokens: 4096
    max_num_seqs: 1024
    log_prob_micro_batch_size_per_gpu: 8
    log_prob_use_dynamic_bsz: True
    log_prob_max_token_len_per_gpu: 16384
    disable_log_stats: True
    enable_chunked_prefill: True
    do_sample: True
    n: 32

algorithm:
  kl_ctrl:
    kl_coef: 0.001
  adv_estimator: grpo

trainer:
  total_epochs: 100
  project_name: grpo_toy_multistep
  experiment_name: v5_3
  logger: [ 'console', 'wandb' ]
  val_before_train: False
  nnodes: 1
  n_gpus_per_node: 1
  save_freq: 40
  test_freq: 5
  critic_warmup: 0
  default_local_dir: ./data/verl/${trainer.project_name}/${trainer.experiment_name}
